#!/bin/bash
#
# You'll need to provide port number with the url.
# Example Web server: test.com:443
# Example WSO2 EI Server: localhost:9443

export SITE_URL=$1
echo QUIT | openssl s_client -connect ${SITE_URL} \
  -servername ${SITE_URL} 2> /dev/null |  openssl x509 -noout  -dates  
