#!/bin/bash
#
# You'll need to provide port number with the url.
# Example Web server: test.com:443
# Example WSO2 EI Server: localhost:9443

openssl s_client -connect $1 </dev/null | openssl x509 -outform pem > tmpcert.pem
openssl x509 -in tmpcert.pem -noout -serial -dates
cat tmpcert.pem
